# Generated by Django 4.0.3 on 2022-11-04 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_attributes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='type',
            new_name='attribute_type',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=models.JSONField(default={}, null=True),
        ),
    ]
